/*
Trader API - Account Access and User Preferences

Testing OrdersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/kebroad/schwab-accounts-and-trading-production-go"
)

func Test_client_OrdersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OrdersAPIService CancelOrder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountNumber string
		var orderId int64

		httpRes, err := apiClient.OrdersAPI.CancelOrder(context.Background(), accountNumber, orderId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrdersAPIService GetOrder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountNumber string
		var orderId int64

		resp, httpRes, err := apiClient.OrdersAPI.GetOrder(context.Background(), accountNumber, orderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrdersAPIService GetOrdersByPathParam", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountNumber string

		resp, httpRes, err := apiClient.OrdersAPI.GetOrdersByPathParam(context.Background(), accountNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrdersAPIService GetOrdersByQueryParam", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OrdersAPI.GetOrdersByQueryParam(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrdersAPIService PlaceOrder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountNumber string

		httpRes, err := apiClient.OrdersAPI.PlaceOrder(context.Background(), accountNumber).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrdersAPIService PreviewOrder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountNumber string

		resp, httpRes, err := apiClient.OrdersAPI.PreviewOrder(context.Background(), accountNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrdersAPIService ReplaceOrder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountNumber string
		var orderId int64

		httpRes, err := apiClient.OrdersAPI.ReplaceOrder(context.Background(), accountNumber, orderId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
