/*
Trader API - Account Access and User Preferences

Schwab Trader API access to Account, Order entry and User Preferences

API version: 1.0.0
Contact: TraderAPI@Schwab.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the TransactionAPIOptionDeliverable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionAPIOptionDeliverable{}

// TransactionAPIOptionDeliverable struct for TransactionAPIOptionDeliverable
type TransactionAPIOptionDeliverable struct {
	RootSymbol *string `json:"rootSymbol,omitempty"`
	StrikePercent *int64 `json:"strikePercent,omitempty"`
	DeliverableNumber *int64 `json:"deliverableNumber,omitempty"`
	DeliverableUnits *float64 `json:"deliverableUnits,omitempty"`
	Deliverable interface{} `json:"deliverable,omitempty"`
	AssetType *AssetType `json:"assetType,omitempty"`
}

// NewTransactionAPIOptionDeliverable instantiates a new TransactionAPIOptionDeliverable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionAPIOptionDeliverable() *TransactionAPIOptionDeliverable {
	this := TransactionAPIOptionDeliverable{}
	return &this
}

// NewTransactionAPIOptionDeliverableWithDefaults instantiates a new TransactionAPIOptionDeliverable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionAPIOptionDeliverableWithDefaults() *TransactionAPIOptionDeliverable {
	this := TransactionAPIOptionDeliverable{}
	return &this
}

// GetRootSymbol returns the RootSymbol field value if set, zero value otherwise.
func (o *TransactionAPIOptionDeliverable) GetRootSymbol() string {
	if o == nil || IsNil(o.RootSymbol) {
		var ret string
		return ret
	}
	return *o.RootSymbol
}

// GetRootSymbolOk returns a tuple with the RootSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionAPIOptionDeliverable) GetRootSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.RootSymbol) {
		return nil, false
	}
	return o.RootSymbol, true
}

// HasRootSymbol returns a boolean if a field has been set.
func (o *TransactionAPIOptionDeliverable) HasRootSymbol() bool {
	if o != nil && !IsNil(o.RootSymbol) {
		return true
	}

	return false
}

// SetRootSymbol gets a reference to the given string and assigns it to the RootSymbol field.
func (o *TransactionAPIOptionDeliverable) SetRootSymbol(v string) {
	o.RootSymbol = &v
}

// GetStrikePercent returns the StrikePercent field value if set, zero value otherwise.
func (o *TransactionAPIOptionDeliverable) GetStrikePercent() int64 {
	if o == nil || IsNil(o.StrikePercent) {
		var ret int64
		return ret
	}
	return *o.StrikePercent
}

// GetStrikePercentOk returns a tuple with the StrikePercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionAPIOptionDeliverable) GetStrikePercentOk() (*int64, bool) {
	if o == nil || IsNil(o.StrikePercent) {
		return nil, false
	}
	return o.StrikePercent, true
}

// HasStrikePercent returns a boolean if a field has been set.
func (o *TransactionAPIOptionDeliverable) HasStrikePercent() bool {
	if o != nil && !IsNil(o.StrikePercent) {
		return true
	}

	return false
}

// SetStrikePercent gets a reference to the given int64 and assigns it to the StrikePercent field.
func (o *TransactionAPIOptionDeliverable) SetStrikePercent(v int64) {
	o.StrikePercent = &v
}

// GetDeliverableNumber returns the DeliverableNumber field value if set, zero value otherwise.
func (o *TransactionAPIOptionDeliverable) GetDeliverableNumber() int64 {
	if o == nil || IsNil(o.DeliverableNumber) {
		var ret int64
		return ret
	}
	return *o.DeliverableNumber
}

// GetDeliverableNumberOk returns a tuple with the DeliverableNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionAPIOptionDeliverable) GetDeliverableNumberOk() (*int64, bool) {
	if o == nil || IsNil(o.DeliverableNumber) {
		return nil, false
	}
	return o.DeliverableNumber, true
}

// HasDeliverableNumber returns a boolean if a field has been set.
func (o *TransactionAPIOptionDeliverable) HasDeliverableNumber() bool {
	if o != nil && !IsNil(o.DeliverableNumber) {
		return true
	}

	return false
}

// SetDeliverableNumber gets a reference to the given int64 and assigns it to the DeliverableNumber field.
func (o *TransactionAPIOptionDeliverable) SetDeliverableNumber(v int64) {
	o.DeliverableNumber = &v
}

// GetDeliverableUnits returns the DeliverableUnits field value if set, zero value otherwise.
func (o *TransactionAPIOptionDeliverable) GetDeliverableUnits() float64 {
	if o == nil || IsNil(o.DeliverableUnits) {
		var ret float64
		return ret
	}
	return *o.DeliverableUnits
}

// GetDeliverableUnitsOk returns a tuple with the DeliverableUnits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionAPIOptionDeliverable) GetDeliverableUnitsOk() (*float64, bool) {
	if o == nil || IsNil(o.DeliverableUnits) {
		return nil, false
	}
	return o.DeliverableUnits, true
}

// HasDeliverableUnits returns a boolean if a field has been set.
func (o *TransactionAPIOptionDeliverable) HasDeliverableUnits() bool {
	if o != nil && !IsNil(o.DeliverableUnits) {
		return true
	}

	return false
}

// SetDeliverableUnits gets a reference to the given float64 and assigns it to the DeliverableUnits field.
func (o *TransactionAPIOptionDeliverable) SetDeliverableUnits(v float64) {
	o.DeliverableUnits = &v
}

// GetDeliverable returns the Deliverable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TransactionAPIOptionDeliverable) GetDeliverable() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Deliverable
}

// GetDeliverableOk returns a tuple with the Deliverable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionAPIOptionDeliverable) GetDeliverableOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Deliverable) {
		return nil, false
	}
	return &o.Deliverable, true
}

// HasDeliverable returns a boolean if a field has been set.
func (o *TransactionAPIOptionDeliverable) HasDeliverable() bool {
	if o != nil && !IsNil(o.Deliverable) {
		return true
	}

	return false
}

// SetDeliverable gets a reference to the given interface{} and assigns it to the Deliverable field.
func (o *TransactionAPIOptionDeliverable) SetDeliverable(v interface{}) {
	o.Deliverable = v
}

// GetAssetType returns the AssetType field value if set, zero value otherwise.
func (o *TransactionAPIOptionDeliverable) GetAssetType() AssetType {
	if o == nil || IsNil(o.AssetType) {
		var ret AssetType
		return ret
	}
	return *o.AssetType
}

// GetAssetTypeOk returns a tuple with the AssetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionAPIOptionDeliverable) GetAssetTypeOk() (*AssetType, bool) {
	if o == nil || IsNil(o.AssetType) {
		return nil, false
	}
	return o.AssetType, true
}

// HasAssetType returns a boolean if a field has been set.
func (o *TransactionAPIOptionDeliverable) HasAssetType() bool {
	if o != nil && !IsNil(o.AssetType) {
		return true
	}

	return false
}

// SetAssetType gets a reference to the given AssetType and assigns it to the AssetType field.
func (o *TransactionAPIOptionDeliverable) SetAssetType(v AssetType) {
	o.AssetType = &v
}

func (o TransactionAPIOptionDeliverable) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionAPIOptionDeliverable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RootSymbol) {
		toSerialize["rootSymbol"] = o.RootSymbol
	}
	if !IsNil(o.StrikePercent) {
		toSerialize["strikePercent"] = o.StrikePercent
	}
	if !IsNil(o.DeliverableNumber) {
		toSerialize["deliverableNumber"] = o.DeliverableNumber
	}
	if !IsNil(o.DeliverableUnits) {
		toSerialize["deliverableUnits"] = o.DeliverableUnits
	}
	if o.Deliverable != nil {
		toSerialize["deliverable"] = o.Deliverable
	}
	if !IsNil(o.AssetType) {
		toSerialize["assetType"] = o.AssetType
	}
	return toSerialize, nil
}

type NullableTransactionAPIOptionDeliverable struct {
	value *TransactionAPIOptionDeliverable
	isSet bool
}

func (v NullableTransactionAPIOptionDeliverable) Get() *TransactionAPIOptionDeliverable {
	return v.value
}

func (v *NullableTransactionAPIOptionDeliverable) Set(val *TransactionAPIOptionDeliverable) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionAPIOptionDeliverable) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionAPIOptionDeliverable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionAPIOptionDeliverable(val *TransactionAPIOptionDeliverable) *NullableTransactionAPIOptionDeliverable {
	return &NullableTransactionAPIOptionDeliverable{value: val, isSet: true}
}

func (v NullableTransactionAPIOptionDeliverable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionAPIOptionDeliverable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


