/*
Trader API - Account Access and User Preferences

Schwab Trader API access to Account, Order entry and User Preferences

API version: 1.0.0
Contact: TraderAPI@Schwab.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// StopPriceLinkType the model 'StopPriceLinkType'
type StopPriceLinkType string

// List of stopPriceLinkType
const (
	STOPPRICELINKTYPE_VALUE StopPriceLinkType = "VALUE"
	STOPPRICELINKTYPE_PERCENT StopPriceLinkType = "PERCENT"
	STOPPRICELINKTYPE_TICK StopPriceLinkType = "TICK"
)

// All allowed values of StopPriceLinkType enum
var AllowedStopPriceLinkTypeEnumValues = []StopPriceLinkType{
	"VALUE",
	"PERCENT",
	"TICK",
}

func (v *StopPriceLinkType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := StopPriceLinkType(value)
	for _, existing := range AllowedStopPriceLinkTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid StopPriceLinkType", value)
}

// NewStopPriceLinkTypeFromValue returns a pointer to a valid StopPriceLinkType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStopPriceLinkTypeFromValue(v string) (*StopPriceLinkType, error) {
	ev := StopPriceLinkType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for StopPriceLinkType: valid values are %v", v, AllowedStopPriceLinkTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v StopPriceLinkType) IsValid() bool {
	for _, existing := range AllowedStopPriceLinkTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to stopPriceLinkType value
func (v StopPriceLinkType) Ptr() *StopPriceLinkType {
	return &v
}

type NullableStopPriceLinkType struct {
	value *StopPriceLinkType
	isSet bool
}

func (v NullableStopPriceLinkType) Get() *StopPriceLinkType {
	return v.value
}

func (v *NullableStopPriceLinkType) Set(val *StopPriceLinkType) {
	v.value = val
	v.isSet = true
}

func (v NullableStopPriceLinkType) IsSet() bool {
	return v.isSet
}

func (v *NullableStopPriceLinkType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStopPriceLinkType(val *StopPriceLinkType) *NullableStopPriceLinkType {
	return &NullableStopPriceLinkType{value: val, isSet: true}
}

func (v NullableStopPriceLinkType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStopPriceLinkType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

