/*
Trader API - Account Access and User Preferences

Schwab Trader API access to Account, Order entry and User Preferences

API version: 1.0.0
Contact: TraderAPI@Schwab.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// Session the model 'Session'
type Session string

// List of session
const (
	SESSION_NORMAL Session = "NORMAL"
	SESSION_AM Session = "AM"
	SESSION_PM Session = "PM"
	SESSION_SEAMLESS Session = "SEAMLESS"
)

// All allowed values of Session enum
var AllowedSessionEnumValues = []Session{
	"NORMAL",
	"AM",
	"PM",
	"SEAMLESS",
}

func (v *Session) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Session(value)
	for _, existing := range AllowedSessionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Session", value)
}

// NewSessionFromValue returns a pointer to a valid Session
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSessionFromValue(v string) (*Session, error) {
	ev := Session(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Session: valid values are %v", v, AllowedSessionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Session) IsValid() bool {
	for _, existing := range AllowedSessionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to session value
func (v Session) Ptr() *Session {
	return &v
}

type NullableSession struct {
	value *Session
	isSet bool
}

func (v NullableSession) Get() *Session {
	return v.value
}

func (v *NullableSession) Set(val *Session) {
	v.value = val
	v.isSet = true
}

func (v NullableSession) IsSet() bool {
	return v.isSet
}

func (v *NullableSession) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSession(val *Session) *NullableSession {
	return &NullableSession{value: val, isSet: true}
}

func (v NullableSession) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSession) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

