/*
Trader API - Account Access and User Preferences

Schwab Trader API access to Account, Order entry and User Preferences

API version: 1.0.0
Contact: TraderAPI@Schwab.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AccountFixedIncome type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountFixedIncome{}

// AccountFixedIncome struct for AccountFixedIncome
type AccountFixedIncome struct {
	MaturityDate *time.Time `json:"maturityDate,omitempty"`
	Factor *float64 `json:"factor,omitempty"`
	VariableRate *float64 `json:"variableRate,omitempty"`
	AssetType string `json:"assetType"`
	Cusip *string `json:"cusip,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
	Description *string `json:"description,omitempty"`
	InstrumentId *int64 `json:"instrumentId,omitempty"`
	NetChange *float64 `json:"netChange,omitempty"`
}

type _AccountFixedIncome AccountFixedIncome

// NewAccountFixedIncome instantiates a new AccountFixedIncome object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountFixedIncome(assetType string) *AccountFixedIncome {
	this := AccountFixedIncome{}
	this.AssetType = assetType
	return &this
}

// NewAccountFixedIncomeWithDefaults instantiates a new AccountFixedIncome object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountFixedIncomeWithDefaults() *AccountFixedIncome {
	this := AccountFixedIncome{}
	return &this
}

// GetMaturityDate returns the MaturityDate field value if set, zero value otherwise.
func (o *AccountFixedIncome) GetMaturityDate() time.Time {
	if o == nil || IsNil(o.MaturityDate) {
		var ret time.Time
		return ret
	}
	return *o.MaturityDate
}

// GetMaturityDateOk returns a tuple with the MaturityDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountFixedIncome) GetMaturityDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.MaturityDate) {
		return nil, false
	}
	return o.MaturityDate, true
}

// HasMaturityDate returns a boolean if a field has been set.
func (o *AccountFixedIncome) HasMaturityDate() bool {
	if o != nil && !IsNil(o.MaturityDate) {
		return true
	}

	return false
}

// SetMaturityDate gets a reference to the given time.Time and assigns it to the MaturityDate field.
func (o *AccountFixedIncome) SetMaturityDate(v time.Time) {
	o.MaturityDate = &v
}

// GetFactor returns the Factor field value if set, zero value otherwise.
func (o *AccountFixedIncome) GetFactor() float64 {
	if o == nil || IsNil(o.Factor) {
		var ret float64
		return ret
	}
	return *o.Factor
}

// GetFactorOk returns a tuple with the Factor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountFixedIncome) GetFactorOk() (*float64, bool) {
	if o == nil || IsNil(o.Factor) {
		return nil, false
	}
	return o.Factor, true
}

// HasFactor returns a boolean if a field has been set.
func (o *AccountFixedIncome) HasFactor() bool {
	if o != nil && !IsNil(o.Factor) {
		return true
	}

	return false
}

// SetFactor gets a reference to the given float64 and assigns it to the Factor field.
func (o *AccountFixedIncome) SetFactor(v float64) {
	o.Factor = &v
}

// GetVariableRate returns the VariableRate field value if set, zero value otherwise.
func (o *AccountFixedIncome) GetVariableRate() float64 {
	if o == nil || IsNil(o.VariableRate) {
		var ret float64
		return ret
	}
	return *o.VariableRate
}

// GetVariableRateOk returns a tuple with the VariableRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountFixedIncome) GetVariableRateOk() (*float64, bool) {
	if o == nil || IsNil(o.VariableRate) {
		return nil, false
	}
	return o.VariableRate, true
}

// HasVariableRate returns a boolean if a field has been set.
func (o *AccountFixedIncome) HasVariableRate() bool {
	if o != nil && !IsNil(o.VariableRate) {
		return true
	}

	return false
}

// SetVariableRate gets a reference to the given float64 and assigns it to the VariableRate field.
func (o *AccountFixedIncome) SetVariableRate(v float64) {
	o.VariableRate = &v
}

// GetAssetType returns the AssetType field value
func (o *AccountFixedIncome) GetAssetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetType
}

// GetAssetTypeOk returns a tuple with the AssetType field value
// and a boolean to check if the value has been set.
func (o *AccountFixedIncome) GetAssetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetType, true
}

// SetAssetType sets field value
func (o *AccountFixedIncome) SetAssetType(v string) {
	o.AssetType = v
}

// GetCusip returns the Cusip field value if set, zero value otherwise.
func (o *AccountFixedIncome) GetCusip() string {
	if o == nil || IsNil(o.Cusip) {
		var ret string
		return ret
	}
	return *o.Cusip
}

// GetCusipOk returns a tuple with the Cusip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountFixedIncome) GetCusipOk() (*string, bool) {
	if o == nil || IsNil(o.Cusip) {
		return nil, false
	}
	return o.Cusip, true
}

// HasCusip returns a boolean if a field has been set.
func (o *AccountFixedIncome) HasCusip() bool {
	if o != nil && !IsNil(o.Cusip) {
		return true
	}

	return false
}

// SetCusip gets a reference to the given string and assigns it to the Cusip field.
func (o *AccountFixedIncome) SetCusip(v string) {
	o.Cusip = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *AccountFixedIncome) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountFixedIncome) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *AccountFixedIncome) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *AccountFixedIncome) SetSymbol(v string) {
	o.Symbol = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AccountFixedIncome) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountFixedIncome) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AccountFixedIncome) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AccountFixedIncome) SetDescription(v string) {
	o.Description = &v
}

// GetInstrumentId returns the InstrumentId field value if set, zero value otherwise.
func (o *AccountFixedIncome) GetInstrumentId() int64 {
	if o == nil || IsNil(o.InstrumentId) {
		var ret int64
		return ret
	}
	return *o.InstrumentId
}

// GetInstrumentIdOk returns a tuple with the InstrumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountFixedIncome) GetInstrumentIdOk() (*int64, bool) {
	if o == nil || IsNil(o.InstrumentId) {
		return nil, false
	}
	return o.InstrumentId, true
}

// HasInstrumentId returns a boolean if a field has been set.
func (o *AccountFixedIncome) HasInstrumentId() bool {
	if o != nil && !IsNil(o.InstrumentId) {
		return true
	}

	return false
}

// SetInstrumentId gets a reference to the given int64 and assigns it to the InstrumentId field.
func (o *AccountFixedIncome) SetInstrumentId(v int64) {
	o.InstrumentId = &v
}

// GetNetChange returns the NetChange field value if set, zero value otherwise.
func (o *AccountFixedIncome) GetNetChange() float64 {
	if o == nil || IsNil(o.NetChange) {
		var ret float64
		return ret
	}
	return *o.NetChange
}

// GetNetChangeOk returns a tuple with the NetChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountFixedIncome) GetNetChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.NetChange) {
		return nil, false
	}
	return o.NetChange, true
}

// HasNetChange returns a boolean if a field has been set.
func (o *AccountFixedIncome) HasNetChange() bool {
	if o != nil && !IsNil(o.NetChange) {
		return true
	}

	return false
}

// SetNetChange gets a reference to the given float64 and assigns it to the NetChange field.
func (o *AccountFixedIncome) SetNetChange(v float64) {
	o.NetChange = &v
}

func (o AccountFixedIncome) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountFixedIncome) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaturityDate) {
		toSerialize["maturityDate"] = o.MaturityDate
	}
	if !IsNil(o.Factor) {
		toSerialize["factor"] = o.Factor
	}
	if !IsNil(o.VariableRate) {
		toSerialize["variableRate"] = o.VariableRate
	}
	toSerialize["assetType"] = o.AssetType
	if !IsNil(o.Cusip) {
		toSerialize["cusip"] = o.Cusip
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.InstrumentId) {
		toSerialize["instrumentId"] = o.InstrumentId
	}
	if !IsNil(o.NetChange) {
		toSerialize["netChange"] = o.NetChange
	}
	return toSerialize, nil
}

func (o *AccountFixedIncome) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"assetType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountFixedIncome := _AccountFixedIncome{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountFixedIncome)

	if err != nil {
		return err
	}

	*o = AccountFixedIncome(varAccountFixedIncome)

	return err
}

type NullableAccountFixedIncome struct {
	value *AccountFixedIncome
	isSet bool
}

func (v NullableAccountFixedIncome) Get() *AccountFixedIncome {
	return v.value
}

func (v *NullableAccountFixedIncome) Set(val *AccountFixedIncome) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountFixedIncome) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountFixedIncome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountFixedIncome(val *AccountFixedIncome) *NullableAccountFixedIncome {
	return &NullableAccountFixedIncome{value: val, isSet: true}
}

func (v NullableAccountFixedIncome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountFixedIncome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


