/*
Trader API - Account Access and User Preferences

Schwab Trader API access to Account, Order entry and User Preferences

API version: 1.0.0
Contact: TraderAPI@Schwab.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the CashAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CashAccount{}

// CashAccount struct for CashAccount
type CashAccount struct {
	SecuritiesAccountBase
	InitialBalances *CashInitialBalance `json:"initialBalances,omitempty"`
	CurrentBalances *CashBalance `json:"currentBalances,omitempty"`
	ProjectedBalances *CashBalance `json:"projectedBalances,omitempty"`
}

// NewCashAccount instantiates a new CashAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCashAccount() *CashAccount {
	this := CashAccount{}
	var isDayTrader bool = false
	this.IsDayTrader = &isDayTrader
	var isClosingOnlyRestricted bool = false
	this.IsClosingOnlyRestricted = &isClosingOnlyRestricted
	var pfcbFlag bool = false
	this.PfcbFlag = &pfcbFlag
	return &this
}

// NewCashAccountWithDefaults instantiates a new CashAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCashAccountWithDefaults() *CashAccount {
	this := CashAccount{}
	return &this
}

// GetInitialBalances returns the InitialBalances field value if set, zero value otherwise.
func (o *CashAccount) GetInitialBalances() CashInitialBalance {
	if o == nil || IsNil(o.InitialBalances) {
		var ret CashInitialBalance
		return ret
	}
	return *o.InitialBalances
}

// GetInitialBalancesOk returns a tuple with the InitialBalances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashAccount) GetInitialBalancesOk() (*CashInitialBalance, bool) {
	if o == nil || IsNil(o.InitialBalances) {
		return nil, false
	}
	return o.InitialBalances, true
}

// HasInitialBalances returns a boolean if a field has been set.
func (o *CashAccount) HasInitialBalances() bool {
	if o != nil && !IsNil(o.InitialBalances) {
		return true
	}

	return false
}

// SetInitialBalances gets a reference to the given CashInitialBalance and assigns it to the InitialBalances field.
func (o *CashAccount) SetInitialBalances(v CashInitialBalance) {
	o.InitialBalances = &v
}

// GetCurrentBalances returns the CurrentBalances field value if set, zero value otherwise.
func (o *CashAccount) GetCurrentBalances() CashBalance {
	if o == nil || IsNil(o.CurrentBalances) {
		var ret CashBalance
		return ret
	}
	return *o.CurrentBalances
}

// GetCurrentBalancesOk returns a tuple with the CurrentBalances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashAccount) GetCurrentBalancesOk() (*CashBalance, bool) {
	if o == nil || IsNil(o.CurrentBalances) {
		return nil, false
	}
	return o.CurrentBalances, true
}

// HasCurrentBalances returns a boolean if a field has been set.
func (o *CashAccount) HasCurrentBalances() bool {
	if o != nil && !IsNil(o.CurrentBalances) {
		return true
	}

	return false
}

// SetCurrentBalances gets a reference to the given CashBalance and assigns it to the CurrentBalances field.
func (o *CashAccount) SetCurrentBalances(v CashBalance) {
	o.CurrentBalances = &v
}

// GetProjectedBalances returns the ProjectedBalances field value if set, zero value otherwise.
func (o *CashAccount) GetProjectedBalances() CashBalance {
	if o == nil || IsNil(o.ProjectedBalances) {
		var ret CashBalance
		return ret
	}
	return *o.ProjectedBalances
}

// GetProjectedBalancesOk returns a tuple with the ProjectedBalances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashAccount) GetProjectedBalancesOk() (*CashBalance, bool) {
	if o == nil || IsNil(o.ProjectedBalances) {
		return nil, false
	}
	return o.ProjectedBalances, true
}

// HasProjectedBalances returns a boolean if a field has been set.
func (o *CashAccount) HasProjectedBalances() bool {
	if o != nil && !IsNil(o.ProjectedBalances) {
		return true
	}

	return false
}

// SetProjectedBalances gets a reference to the given CashBalance and assigns it to the ProjectedBalances field.
func (o *CashAccount) SetProjectedBalances(v CashBalance) {
	o.ProjectedBalances = &v
}

func (o CashAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CashAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedSecuritiesAccountBase, errSecuritiesAccountBase := json.Marshal(o.SecuritiesAccountBase)
	if errSecuritiesAccountBase != nil {
		return map[string]interface{}{}, errSecuritiesAccountBase
	}
	errSecuritiesAccountBase = json.Unmarshal([]byte(serializedSecuritiesAccountBase), &toSerialize)
	if errSecuritiesAccountBase != nil {
		return map[string]interface{}{}, errSecuritiesAccountBase
	}
	if !IsNil(o.InitialBalances) {
		toSerialize["initialBalances"] = o.InitialBalances
	}
	if !IsNil(o.CurrentBalances) {
		toSerialize["currentBalances"] = o.CurrentBalances
	}
	if !IsNil(o.ProjectedBalances) {
		toSerialize["projectedBalances"] = o.ProjectedBalances
	}
	return toSerialize, nil
}

type NullableCashAccount struct {
	value *CashAccount
	isSet bool
}

func (v NullableCashAccount) Get() *CashAccount {
	return v.value
}

func (v *NullableCashAccount) Set(val *CashAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableCashAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableCashAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCashAccount(val *CashAccount) *NullableCashAccount {
	return &NullableCashAccount{value: val, isSet: true}
}

func (v NullableCashAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCashAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


